const listaProdutos = [
  {
    idproduto: 1,
    idcategoria: 1,
    descricao:
      "Geladeira/Refrigerador Side By Side Frost Free Inox 504L Electrolux",
    preco_antigo: 9789.05,
    preco: 7789.05,
    imagem: "./img/geladeira-eletrolux.png",
    categoria: "Geladeira",
  },
  {
    idproduto: 6,
    idcategoria: 1,
    descricao: "Geladeira/Refrigerador Frost Free 310 Litros Branco Electrolux",
    preco_antigo: 2299.1,
    preco: 1799.1,
    imagem: "./img/geladeira-eletrolux2.png",
    categoria: "Geladeira",
  },
  {
    idproduto: 2,
    idcategoria: 2,
    descricao: "Micro-Ondas 34L Preto Pro Series Electrolux",
    preco_antigo: 4799,
    preco: 4399,
    imagem: "./img/microondas-eletrolux.png",
    categoria: "Microondas",
  },
  {
    idproduto: 3,
    idcategoria: 2,
    descricao: "Micro-ondas Branco com Função Tira Odor e Manter Aquecido 34L",
    preco_antigo: 1039.1,
    preco: 539.1,
    imagem: "./img/microondas-eletrolux2.png",
    categoria: "Microondas",
  },
  {
    idproduto: 4,
    idcategoria: 3,
    descricao:
      "Fogão 5 Bocas Electrolux Prata Aut.com Mesa de Vidro e Tripla Chama",
    preco_antigo: 2189.05,
    preco: 2089.05,
    imagem: "./img/fogao-eletrolux1.png",
    categoria: "Fogao",
  },
  {
    idproduto: 8,
    idcategoria: 3,
    descricao:
      "Fogão 4 Bocas Electrolux Branco Aut. com Timer Digital e Forno de 70L",
    preco_antigo: 1249.55,
    preco: 1186.55,
    imagem: "./img/fogao-eletrolux2.png",
    categoria: "Fogao",
  },
  {
    idproduto: 5,
    idcategoria: 4,
    descricao: "Lava-Louças Electrolux 8 Serviços e 5 velocidades Cinza",
    preco_antigo: 2949.1,
    preco: 2249.1,
    imagem: "./img/lava-lou%C3%A7as1.png",
    categoria: "Lava-loucas",
  },
  {
    idproduto: 7,
    idcategoria: 5,
    descricao:
      "Lava e Seca 11Kg/7Kg Electrolux Prata com Wi-fI e Água Quente/Vapor",
    preco_antigo: 4999.05,
    preco: 4084.05,
    imagem: "./img/lava-roupas.png",
    categoria: "Lava-roupas",
  },
  {
    idproduto: 9,
    idcategoria: 6,
    descricao: "Adega 8 Garrafas Com Acabamento Em Alumínio Escovado",
    preco_antigo: 929,
    preco: 674.1,
    imagem: "./img/adega.png",
    categoria: "Adega",
  },
  {
    idproduto: 10,
    idcategoria: 7,
    descricao:
      "Ar-Condicionado Inverter Split 9000 BTUs Electrolux Frio com Wi-fi - 220V",
    preco_antigo: 1949,
    preco: 1851.55,
    imagem: "./img/ar-condicionado.png",
    categoria: "Ar-condicionado",
  },
  {
    idproduto: 11,
    idcategoria: 8,
    descricao: "Purificador de Água Prata com Painel Touch Bivolt",
    preco_antigo: 729,
    preco: 559.55,
    imagem: "./img/purificador-agua.png",
    categoria: "Filtro",
  },
  {
    idproduto: 12,
    idcategoria: 9,
    descricao: "Cafeteira Expressionist Display LCD Programável Electrolux",
    preco_antigo: 849.9,
    preco: 599.9,
    imagem: "./img/cafeteira.png",
    categoria: "Cafeteira",
  },
];

export default listaProdutos;
